# Generated by Django 4.1.3 on 2022-11-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("dish_type__name",), "verbose_name_plural": "dishes"},
        ),
        migrations.AlterField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to="kitchen_service.ingredients"
            ),
        ),
    ]
