# Generated by Django 4.1.3 on 2022-11-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0002_alter_dish_options_alter_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="recipe",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="dish",
                to="kitchen_service.recipe",
            ),
        ),
    ]
