# Generated by Django 4.1.3 on 2022-12-01 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0004_alter_dish_cooks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name_plural": "dishes"},
        ),
        migrations.RemoveField(
            model_name="dish",
            name="ingredients",
        ),
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="dish",
                to="kitchen_service.recipe",
            ),
        ),
    ]
