# Generated by Django 4.1.3 on 2022-12-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0006_alter_dish_recipe"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingredients",
            new_name="Ingredient",
        ),
    ]
