# Generated by Django 4.1.3 on 2022-12-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0007_rename_ingredients_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="recipe",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes", to="kitchen_service.ingredient"
            ),
        ),
    ]
