# Generated by Django 4.1.3 on 2022-12-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0009_alter_dish_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="recipe",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish",
                to="kitchen_service.recipe",
            ),
        ),
    ]
