# Generated by Django 4.1.3 on 2022-12-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0010_alter_dish_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="recipe",
        ),
        migrations.AddField(
            model_name="recipe",
            name="dish",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="kitchen_service.dish",
            ),
        ),
    ]
