# Generated by Django 4.1.3 on 2022-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0011_remove_dish_recipe_recipe_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("grill", "grill"),
                    ("assistant", "assistant"),
                    ("pizzmaker", "pizzmaker"),
                    ("sushi maker", "sushi maker"),
                ],
                default="assistant",
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
