# Generated by Django 4.1.3 on 2022-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0012_alter_cook_specialization_alter_dish_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("chef", "chef"),
                    ("grill", "grill"),
                    ("assistant", "assistant"),
                    ("pizzmaker", "pizzmaker"),
                    ("sushi maker", "sushi maker"),
                ],
                default="assistant",
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipe", to="kitchen_service.ingredient"
            ),
        ),
    ]
