# Generated by Django 4.1.3 on 2022-12-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0013_alter_cook_specialization_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("chef", "chef"),
                    ("grill", "grill"),
                    ("assistant", "assistant"),
                    ("pizzmaker", "pizzmaker"),
                    ("sushi maker", "sushi maker"),
                    ("prep cook", "prep cook"),
                ],
                default="assistant",
                max_length=63,
            ),
        ),
    ]
