# Generated by Django 4.1.3 on 2022-12-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0014_alter_cook_specialization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.RemoveField(
            model_name="message",
            name="liked",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
