# Generated by Django 4.1.3 on 2022-12-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen_service", "0016_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("dish_type",), "verbose_name_plural": "dishes"},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="dish",
        ),
        migrations.AddField(
            model_name="dish",
            name="recipe",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish",
                to="kitchen_service.recipe",
            ),
        ),
    ]
