from django.urls import path

from kitchen_service.views import (index,
                                   DishTypeListView,
                                   DishTypeUpdateView,
                                   DishTypeCreateView,
                                   DishTypeDeleteView,
                                   DishListView,
                                   DishDetailView,
                                   DishCreateView,
                                   DishUpdateView,
                                   DishDeleteView,
                                   CookListView,
                                   CookCreateView,
                                   CookDetailView,
                                   CookDeleteView,
                                   RecipeDetailView,
                                   RecipeCreateView,
                                   RecipeUpdateView,
                                   RecipeDeleteView,
                                   toggle_me_to_dish,
                                   TaskListView,
                                   mark_complete_or_undo,
                                   TaskCreateView,
                                   TaskUpdateView,
                                   TaskDeleteView,
                                   )

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/toggle_me_to_dish/", toggle_me_to_dish, name="toggle_me_to_dish"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("recipe/<int:pk>/", RecipeDetailView.as_view(), name="recipe-detail"),
    path("dishes/<int:pk>/recipe-create/", RecipeCreateView.as_view(), name="recipe-create"),
    path("recipe/<int:pk>/update/", RecipeUpdateView.as_view(), name="recipe-update"),
    path("recipe/<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/mark_task/", mark_complete_or_undo, name="task-mark"),
                ]


app_name = "kitchen_service"
